### ISSUE TITLE
Anzahl Beobachtungen verschwindet mit Verbindungslinie

### ISSUE THREAD

**Issue by wunderli** [barbalex/apf2#175]
Lieber Alex

Beim Einblenden der Verbindungslinien der zugeordneten Beobachtungen verschwindet die Anzahl Beobachtungen, die sich genau am selben Ort sind.
Wäre super, wenn wieder die Anzahl Beobachtungen angezeigt werden könnte.

![bildschirmfoto 2018-08-31 um 15 36 10](https://user-images.githubusercontent.com/26789445/44915652-cbdd1080-ad33-11e8-966d-c70226e472dc.png)
![bildschirmfoto 2018-08-31 um 15 36 16](https://user-images.githubusercontent.com/26789445/44915658-ce3f6a80-ad33-11e8-8f43-65417a1880a2.png)

**Comment by barbalex** [comment]
Das ist so "by design", weil der Zweck der Verbindungslinien ist, beim Zuordnen auf der Karte zu zeigen, was noch nicht zugeordnet ist.

Beim Zuordnen muss man die einzelnen TPop sehen, um zuordnen zu können.

Und die Darstellung mit der Anzahl fasst je nach Zoomstufe die Anzahl zusammen und stellt sie dann nicht mehr einzeln dar. Ist also nicht zum Zuordnen geeignet.
